#! /bin/sh
# $1 - in  file
# $2 - out file
# $3 - os
# $4 - is bundled curl on/off flag
# $5 - curl symbols
# $6 - export templates
if [ "x$3x" = xDarwinx ]; then
    # _func1
    # _func2
    sed -e 's/#.*//; /^[[:space:]]*$/d; s/^/_/;' $1 > $2
    if [ "x$4x" = xONx ]; then
      sed -e 's/#.*//; /^[[:space:]]*$/d; s/^/_/;' $5 >> $2
    fi
else
    # {
    #   func1;
    #   func2;
    # };
    echo "$6"
    ( echo "{" && {
      # combine static defined list of functions
      cat $1 ;
      # with list of exported functions of bundled libraries
      if [ "x$4x" = xONx ]; then
        cat $5
      fi ;
      for so in $6 ; do {
        # exported names from shared object
        nm -D $so ||
        # or follow patch from shared object script
        nm -D `cat $so | grep GROUP | awk '{print $3}'` ;
      } | awk '{print $3}' ; done ;
    } | sed '/^\s*$/d;s/$/;/;' && echo "};" ) > $2
fi
