name: release

on:
  push:
  pull_request:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

env:
  CI_MAKE: make -f .travis.mk

jobs:
  release:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: ( github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository ) &&
        ! endsWith(github.ref, '-notest')

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    steps:
      - name: disable swap and cleanup sources repository
        shell: bash
        run: |
          sudo /bin/bash -c "echo 0 >/sys/fs/cgroup/memory/memory.swappiness"
          [ ! -d .git ] || sudo /bin/bash -c "git clean -xfd && git submodule foreach git clean -xfd"
      - uses: actions/checkout@v2.3.4
      - name: cleanup repository tags
        shell: bash
        run: |
          git describe --exact-match HEAD || git tag -d "$(git tag --points-at HEAD)" 2>/dev/null || true
      - uses: ./.github/actions/environment
      - name: test
        run: ${CI_MAKE} test_debian_no_deps
      - name: call action to send Telegram message on failure
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_CORE_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_CORE_TO }}
        uses: ./.github/actions/send-telegram-notify
        if: failure()
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: release
          retention-days: 21
          path: test/var/artifacts
